/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `tbl_data_cnd`
--

DROP TABLE IF EXISTS `tbl_data_cnd`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `tbl_data_cnd` (
  `BedroomsThird` varchar(32) DEFAULT NULL,
  `LotNum` varchar(32) DEFAULT NULL,
  `OtherRoomOneDesc` varchar(64) DEFAULT NULL,
  `BedroomTwoDim` varchar(32) DEFAULT NULL,
  `Subdivision` varchar(32) DEFAULT NULL,
  `OfficeListOfficeName` varchar(64) DEFAULT NULL,
  `BedroomTwoDesc` varchar(64) DEFAULT NULL,
  `BedroomsMain` varchar(32) DEFAULT NULL,
  `CoolingSystem` varchar(64) DEFAULT NULL,
  `OvenSource` varchar(64) DEFAULT NULL,
  `OtherRoomOneDim` varchar(64) DEFAULT NULL,
  `DiningRoomDim` varchar(64) DEFAULT NULL,
  `AgentCoListFullName` varchar(320) DEFAULT NULL,
  `FloorTypes` varchar(320) DEFAULT NULL,
  `PoolDesc` varchar(320) DEFAULT NULL,
  `PictureCount` int(11) DEFAULT NULL,
  `BedroomFourDim` varchar(64) DEFAULT NULL,
  `OfficeListPhone` varchar(64) DEFAULT NULL,
  `FullBathsOther` varchar(64) DEFAULT NULL,
  `SqFtOtherDescription` varchar(320) DEFAULT NULL,
  `OvenDesc` varchar(320) DEFAULT NULL,
  `SqFtTotal` decimal(10,0) DEFAULT NULL,
  `MasterBathType` varchar(64) DEFAULT NULL,
  `OfficeListCompanyID` varchar(64) DEFAULT NULL,
  `ListingType` varchar(32) DEFAULT NULL,
  `TotalFullBaths` int(11) DEFAULT NULL,
  `HalfBathsBasement` varchar(64) DEFAULT NULL,
  `InteriorOther` varchar(320) DEFAULT NULL,
  `OfficeCoListPhone` varchar(64) DEFAULT NULL,
  `MasterBathDesc` varchar(320) DEFAULT NULL,
  `AppliancesOther` varchar(320) DEFAULT NULL,
  `GreenCertifyingBody` varchar(1024) DEFAULT NULL,
  `ListPrice` decimal(10,0) DEFAULT NULL,
  `CountyID` varchar(32) DEFAULT NULL,
  `OfficeListCode` varchar(64) DEFAULT NULL,
  `BasementType` varchar(64) DEFAULT NULL,
  `Acres` varchar(64) DEFAULT NULL,
  `BedroomsBasement` varchar(64) DEFAULT NULL,
  `HalfBathsThird` varchar(64) DEFAULT NULL,
  `HeatingSystem` varchar(64) DEFAULT NULL,
  `StreetLetter` varchar(64) DEFAULT NULL,
  `RangeDesc` varchar(320) DEFAULT NULL,
  `TotalHalfBaths` int(11) DEFAULT NULL,
  `AreaID` varchar(64) DEFAULT NULL,
  `BedroomThreeDesc` varchar(320) DEFAULT NULL,
  `BuiltInfo` varchar(64) DEFAULT NULL,
  `HighSchool` varchar(64) DEFAULT NULL,
  `PermitExternalComments` varchar(320) DEFAULT NULL,
  `OfficeCoListID` varchar(64) DEFAULT NULL,
  `LotDesc` varchar(320) DEFAULT NULL,
  `YearBuilt` int(11) DEFAULT NULL,
  `AgentListFirstName` varchar(320) DEFAULT NULL,
  `Directions` varchar(1024) DEFAULT NULL,
  `CoolingSource` varchar(64) DEFAULT NULL,
  `NextOpenHouseDate` varchar(64) DEFAULT NULL,
  `ElementarySchool` varchar(64) DEFAULT NULL,
  `AgentCoListFirstName` varchar(64) DEFAULT NULL,
  `LivingRoomDim` varchar(64) DEFAULT NULL,
  `WaterfrontDesc` varchar(320) DEFAULT NULL,
  `ExteriorFeatures` varchar(1024) DEFAULT NULL,
  `Remarks` varchar(1024) DEFAULT NULL,
  `AgentCoListID` varchar(64) DEFAULT NULL,
  `City` varchar(32) DEFAULT NULL,
  `ConstructionType` varchar(64) DEFAULT NULL,
  `DiningRoomDesc` varchar(320) DEFAULT NULL,
  `CommunityAmenities` varchar(1024) DEFAULT NULL,
  `MapNumber` varchar(64) DEFAULT NULL,
  `OfficeListID` varchar(64) DEFAULT NULL,
  `TotalBedrooms` int(11) DEFAULT NULL,
  `PropertyClassID` varchar(64) DEFAULT NULL,
  `LivingRoomDesc` varchar(320) DEFAULT NULL,
  `DenDesc` varchar(320) DEFAULT NULL,
  `State` varchar(32) DEFAULT NULL,
  `HalfBathsMain` varchar(64) DEFAULT NULL,
  `OfficeCoListCode` varchar(64) DEFAULT NULL,
  `PropertySubType` varchar(64) DEFAULT NULL,
  `DrapesRemain` varchar(64) DEFAULT NULL,
  `SqFtBasement` decimal(10,0) DEFAULT NULL,
  `AgentListLastName` varchar(64) DEFAULT NULL,
  `HobbyRoomDim` varchar(64) DEFAULT NULL,
  `KitchenDim` varchar(64) DEFAULT NULL,
  `OpenHouseType` varchar(64) DEFAULT NULL,
  `FullBathsSecond` varchar(64) DEFAULT NULL,
  `RecRoomDesc` varchar(320) DEFAULT NULL,
  `SqFtSecondFloor` decimal(10,0) DEFAULT NULL,
  `SewerSystem` varchar(64) DEFAULT NULL,
  `BedroomsOther` varchar(64) DEFAULT NULL,
  `ModDate` varchar(64) DEFAULT NULL,
  `BedroomsSecond` varchar(64) DEFAULT NULL,
  `StreetDirection` varchar(320) DEFAULT NULL,
  `StreetAddressDisplay` varchar(320) DEFAULT NULL,
  `MlsNum` varchar(64) NOT NULL,
  `ExteriorTrim` varchar(64) DEFAULT NULL,
  `JuniorHighSchool` varchar(64) DEFAULT NULL,
  `IsNewConstruction` varchar(32) DEFAULT NULL,
  `WaterfrontDock` varchar(64) DEFAULT NULL,
  `GarageCapacity` varchar(64) DEFAULT NULL,
  `SqFtMeasurementSource` varchar(64) DEFAULT NULL,
  `HalfBathsSecond` varchar(64) DEFAULT NULL,
  `KitchenDesc` varchar(320) DEFAULT NULL,
  `ElementarySchoolTwo` varchar(64) DEFAULT NULL,
  `Longitude` decimal(10,6) DEFAULT NULL,
  `PatioDeck` varchar(1024) DEFAULT NULL,
  `DenDim` varchar(64) DEFAULT NULL,
  `Latitude` decimal(10,6) DEFAULT NULL,
  `OfficeCoListCompanyID` varchar(64) DEFAULT NULL,
  `AgentListID` varchar(64) DEFAULT NULL,
  `ZipCode` varchar(32) DEFAULT NULL,
  `EnergyFeatures` varchar(1024) DEFAULT NULL,
  `OtherRoomTwoDesc` varchar(320) DEFAULT NULL,
  `RangeSource` varchar(64) DEFAULT NULL,
  `BedroomFourDesc` varchar(320) DEFAULT NULL,
  `FullBathsBasement` varchar(64) DEFAULT NULL,
  `RecRoomDim` varchar(64) DEFAULT NULL,
  `TotalRooms` int(11) DEFAULT NULL,
  `AgentListFullName` varchar(320) DEFAULT NULL,
  `BedroomOneDesc` varchar(320) DEFAULT NULL,
  `OfficeCoListOfficeName` varchar(64) DEFAULT NULL,
  `Style` varchar(64) DEFAULT NULL,
  `DrivewayType` varchar(64) DEFAULT NULL,
  `OtherRoomTwoDim` varchar(64) DEFAULT NULL,
  `HobbyRoomDesc` varchar(320) DEFAULT NULL,
  `FenceType` varchar(64) DEFAULT NULL,
  `HandicapAccess` varchar(64) DEFAULT NULL,
  `SqFtThirdFloor` decimal(10,0) DEFAULT NULL,
  `SqFtMainFloor` decimal(10,0) DEFAULT NULL,
  `AgentCoListLastName` varchar(64) DEFAULT NULL,
  `ListingStatusID` varchar(64) DEFAULT NULL,
  `BedroomOneDim` varchar(64) DEFAULT NULL,
  `MiscOther` varchar(1024) DEFAULT NULL,
  `IsCertifiedGreen` varchar(32) DEFAULT NULL,
  `PrimaryPictureURL` varchar(1024) DEFAULT NULL,
  `NumOfStories` int(11) DEFAULT NULL,
  `TaxAmount` varchar(320) DEFAULT NULL,
  `LotSize` varchar(320) DEFAULT NULL,
  `ContingencyType` varchar(320) DEFAULT NULL,
  `StreetNumber` varchar(320) DEFAULT NULL,
  `NumberOfFireplaces` int(11) DEFAULT NULL,
  `BasementDesc` varchar(320) DEFAULT NULL,
  `WaterSource` varchar(64) DEFAULT NULL,
  `FullBathsMain` varchar(64) DEFAULT NULL,
  `AssociationFee` varchar(64) DEFAULT NULL,
  `CompletionDate` varchar(64) DEFAULT NULL,
  `PermitAvmUse` varchar(64) DEFAULT NULL,
  `MediaUpdateDate` varchar(64) DEFAULT NULL,
  `HeatingSource` varchar(64) DEFAULT NULL,
  `RoofMaterial` varchar(64) DEFAULT NULL,
  `FullBathsThird` varchar(64) DEFAULT NULL,
  `SqFtOther` decimal(10,0) DEFAULT NULL,
  `AcreageSource` varchar(64) DEFAULT NULL,
  `StreetName` varchar(320) DEFAULT NULL,
  `GarageDescription` varchar(320) DEFAULT NULL,
  `HalfBathsOther` varchar(64) DEFAULT NULL,
  `AgentListPhone` varchar(64) DEFAULT NULL,
  `BedroomThreeDim` varchar(64) DEFAULT NULL,
  `UnitLocation` varchar(64) DEFAULT NULL,
  `OtherRestrictions` varchar(320) DEFAULT NULL,
  `RentingPermitted` varchar(64) DEFAULT NULL,
  `OfficeListIsIDX` varchar(64) DEFAULT NULL,
  `ExteriorAlterations` varchar(128) DEFAULT NULL,
  `TrailersPermitted` varchar(32) DEFAULT NULL,
  `MailBoxType` varchar(32) DEFAULT NULL,
  `AgentCoListPhone` varchar(64) DEFAULT NULL,
  `VerticalLocation` varchar(64) DEFAULT NULL,
  `HasPetRestriction` varchar(32) DEFAULT NULL,
  `UnitNumber` varchar(32) DEFAULT NULL,
  `WithdrawnDate` varchar(32) DEFAULT NULL,
  `AssociationFeeIncludes` varchar(320) DEFAULT NULL,
  `SecurityDesc` varchar(320) DEFAULT NULL,
  `AbsLatitude` decimal(10,0) NOT NULL,
  `AbsLongitude` decimal(10,0) NOT NULL,
  PRIMARY KEY (`MlsNum`)
) ENGINE=InnoDB DEFAULT CHARSET=big5;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `tbl_data_com`
--

DROP TABLE IF EXISTS `tbl_data_com`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `tbl_data_com` (
  `Zoning` varchar(32) DEFAULT NULL,
  `OfficeListOfficeName` varchar(64) DEFAULT NULL,
  `AgentCoListFullName` varchar(320) DEFAULT NULL,
  `PictureCount` int(11) DEFAULT NULL,
  `OfficeListPhone` varchar(64) DEFAULT NULL,
  `SqFtTotal` decimal(10,0) DEFAULT NULL,
  `OfficeListCompanyID` varchar(64) DEFAULT NULL,
  `ListingType` varchar(32) DEFAULT NULL,
  `OfficeCoListPhone` varchar(64) DEFAULT NULL,
  `ListPrice` decimal(10,0) DEFAULT NULL,
  `CountyID` varchar(32) DEFAULT NULL,
  `OfficeListCode` varchar(64) DEFAULT NULL,
  `IsListedOnInternet` varchar(32) DEFAULT NULL,
  `Acres` varchar(64) DEFAULT NULL,
  `StreetLetter` varchar(64) DEFAULT NULL,
  `AreaID` varchar(64) DEFAULT NULL,
  `IsLeased` varchar(32) DEFAULT NULL,
  `PermitExternalComments` varchar(320) DEFAULT NULL,
  `OfficeCoListID` varchar(64) DEFAULT NULL,
  `AgentListFirstName` varchar(320) DEFAULT NULL,
  `Directions` varchar(1024) DEFAULT NULL,
  `NextOpenHouseDate` varchar(64) DEFAULT NULL,
  `AgentCoListFirstName` varchar(64) DEFAULT NULL,
  `Remarks` varchar(1024) DEFAULT NULL,
  `AgentCoListID` varchar(64) DEFAULT NULL,
  `City` varchar(32) DEFAULT NULL,
  `OfficeListID` varchar(64) DEFAULT NULL,
  `PropertyClassID` varchar(64) DEFAULT NULL,
  `State` varchar(32) DEFAULT NULL,
  `OfficeCoListCode` varchar(64) DEFAULT NULL,
  `PropertySubType` varchar(64) DEFAULT NULL,
  `LeasePerSqFt` varchar(64) DEFAULT NULL,
  `LeasePerMonth` varchar(32) DEFAULT NULL,
  `AgentListLastName` varchar(64) DEFAULT NULL,
  `OpenHouseType` varchar(64) DEFAULT NULL,
  `ModDate` varchar(64) DEFAULT NULL,
  `StreetDirection` varchar(320) DEFAULT NULL,
  `StreetAddressDisplay` varchar(320) DEFAULT NULL,
  `MlsNum` varchar(64) NOT NULL,
  `SqFtMeasurementSource` varchar(64) DEFAULT NULL,
  `Longitude` decimal(10,6) DEFAULT NULL,
  `Latitude` decimal(10,6) DEFAULT NULL,
  `OfficeCoListCompanyID` varchar(64) DEFAULT NULL,
  `AgentListID` varchar(64) DEFAULT NULL,
  `ZipCode` varchar(32) DEFAULT NULL,
  `AgentListFullName` varchar(320) DEFAULT NULL,
  `OfficeCoListOfficeName` varchar(64) DEFAULT NULL,
  `AgentCoListLastName` varchar(64) DEFAULT NULL,
  `ListingStatusID` varchar(64) DEFAULT NULL,
  `PrimaryPictureURL` varchar(1024) DEFAULT NULL,
  `StreetNumber` varchar(320) DEFAULT NULL,
  `PermitAvmUse` varchar(64) DEFAULT NULL,
  `MediaUpdateDate` varchar(64) DEFAULT NULL,
  `RoofMaterial` varchar(64) DEFAULT NULL,
  `AcreageSource` varchar(64) DEFAULT NULL,
  `StreetName` varchar(320) DEFAULT NULL,
  `AgentListPhone` varchar(64) DEFAULT NULL,
  `AgentCoListPhone` varchar(64) DEFAULT NULL,
  `AbsLatitude` decimal(10,0) NOT NULL,
  `AbsLongitude` decimal(10,0) NOT NULL,
  PRIMARY KEY (`MlsNum`)
) ENGINE=InnoDB DEFAULT CHARSET=big5;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `tbl_data_llf`
--

DROP TABLE IF EXISTS `tbl_data_llf`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `tbl_data_llf` (
  `BedroomsThird` varchar(32) DEFAULT NULL,
  `LotNum` varchar(32) DEFAULT NULL,
  `Subdivision` varchar(32) DEFAULT NULL,
  `Zoning` varchar(32) DEFAULT NULL,
  `AcresPasture` varchar(32) DEFAULT NULL,
  `DiningRoomDim` varchar(32) DEFAULT NULL,
  `RoadFrontageDesc` varchar(64) DEFAULT NULL,
  `SaleIncludes` varchar(32) DEFAULT NULL,
  `TerrainType` varchar(32) DEFAULT NULL,
  `AcresFenced` varchar(32) DEFAULT NULL,
  `HasCableTV` varchar(32) DEFAULT NULL,
  `AcresTimber` varchar(32) DEFAULT NULL,
  `Buildings` varchar(32) DEFAULT NULL,
  `IsFederalLandBank` varchar(32) DEFAULT NULL,
  `Restrictions` varchar(32) DEFAULT NULL,
  `AcresTobacco` varchar(32) DEFAULT NULL,
  `MiscOtherTwo` varchar(32) DEFAULT NULL,
  `RoadFrontageDim` varchar(32) DEFAULT NULL,
  `AcresCultivated` varchar(32) DEFAULT NULL,
  `Equipment` varchar(32) DEFAULT NULL,
  `HasHouse` varchar(32) DEFAULT NULL,
  `WaterDesc` varchar(64) DEFAULT NULL,
  `RoadSurface` varchar(32) DEFAULT NULL,
  `OfficeListOfficeName` varchar(64) DEFAULT NULL,
  `CoolingSystem` varchar(64) DEFAULT NULL,
  `AgentCoListFullName` varchar(320) DEFAULT NULL,
  `PictureCount` int(11) DEFAULT NULL,
  `OfficeListPhone` varchar(64) DEFAULT NULL,
  `SqFtTotal` decimal(10,0) DEFAULT NULL,
  `OfficeListCompanyID` varchar(64) DEFAULT NULL,
  `ListingType` varchar(32) DEFAULT NULL,
  `TotalFullBaths` int(11) DEFAULT NULL,
  `OfficeCoListPhone` varchar(64) DEFAULT NULL,
  `AppliancesOther` varchar(320) DEFAULT NULL,
  `ListPrice` decimal(10,0) DEFAULT NULL,
  `CountyID` varchar(32) DEFAULT NULL,
  `OfficeListCode` varchar(64) DEFAULT NULL,
  `Acres` varchar(64) DEFAULT NULL,
  `HeatingSystem` varchar(64) DEFAULT NULL,
  `StreetLetter` varchar(64) DEFAULT NULL,
  `RangeDesc` varchar(320) DEFAULT NULL,
  `TotalHalfBaths` int(11) DEFAULT NULL,
  `AreaID` varchar(64) DEFAULT NULL,
  `BuiltInfo` varchar(64) DEFAULT NULL,
  `HighSchool` varchar(64) DEFAULT NULL,
  `PermitExternalComments` varchar(320) DEFAULT NULL,
  `OfficeCoListID` varchar(64) DEFAULT NULL,
  `YearBuilt` int(11) DEFAULT NULL,
  `AgentListFirstName` varchar(320) DEFAULT NULL,
  `Directions` varchar(1024) DEFAULT NULL,
  `CoolingSource` varchar(64) DEFAULT NULL,
  `NextOpenHouseDate` varchar(64) DEFAULT NULL,
  `ElementarySchool` varchar(64) DEFAULT NULL,
  `AgentCoListFirstName` varchar(64) DEFAULT NULL,
  `LivingRoomDim` varchar(64) DEFAULT NULL,
  `Remarks` varchar(1024) DEFAULT NULL,
  `AgentCoListID` varchar(64) DEFAULT NULL,
  `City` varchar(32) DEFAULT NULL,
  `ConstructionType` varchar(64) DEFAULT NULL,
  `MapNumber` varchar(64) DEFAULT NULL,
  `OfficeListID` varchar(64) DEFAULT NULL,
  `TotalBedrooms` int(11) DEFAULT NULL,
  `PropertyClassID` varchar(64) DEFAULT NULL,
  `State` varchar(32) DEFAULT NULL,
  `OfficeCoListCode` varchar(64) DEFAULT NULL,
  `MasterBedroomDim` varchar(32) DEFAULT NULL,
  `PropertySubType` varchar(64) DEFAULT NULL,
  `SqFtBasement` decimal(10,0) DEFAULT NULL,
  `AgentListLastName` varchar(64) DEFAULT NULL,
  `KitchenDim` varchar(64) DEFAULT NULL,
  `OpenHouseType` varchar(64) DEFAULT NULL,
  `SqFtSecondFloor` decimal(10,0) DEFAULT NULL,
  `SewerSystem` varchar(64) DEFAULT NULL,
  `ModDate` varchar(64) DEFAULT NULL,
  `StreetDirection` varchar(320) DEFAULT NULL,
  `StreetAddressDisplay` varchar(320) DEFAULT NULL,
  `MlsNum` varchar(64) NOT NULL,
  `ExteriorTrim` varchar(64) DEFAULT NULL,
  `JuniorHighSchool` varchar(64) DEFAULT NULL,
  `IsNewConstruction` varchar(32) DEFAULT NULL,
  `GarageCapacity` varchar(64) DEFAULT NULL,
  `SqFtMeasurementSource` varchar(64) DEFAULT NULL,
  `ElementarySchoolTwo` varchar(64) DEFAULT NULL,
  `Longitude` decimal(10,6) DEFAULT NULL,
  `Latitude` decimal(10,6) DEFAULT NULL,
  `OfficeCoListCompanyID` varchar(64) DEFAULT NULL,
  `AgentListID` varchar(64) DEFAULT NULL,
  `ZipCode` varchar(32) DEFAULT NULL,
  `RangeSource` varchar(64) DEFAULT NULL,
  `TotalRooms` int(11) DEFAULT NULL,
  `AgentListFullName` varchar(320) DEFAULT NULL,
  `OfficeCoListOfficeName` varchar(64) DEFAULT NULL,
  `Style` varchar(64) DEFAULT NULL,
  `DrivewayType` varchar(64) DEFAULT NULL,
  `HandicapAccess` varchar(64) DEFAULT NULL,
  `SqFtThirdFloor` decimal(10,0) DEFAULT NULL,
  `SqFtMainFloor` decimal(10,0) DEFAULT NULL,
  `AgentCoListLastName` varchar(64) DEFAULT NULL,
  `ListingStatusID` varchar(64) DEFAULT NULL,
  `PrimaryPictureURL` varchar(1024) DEFAULT NULL,
  `TaxAmount` varchar(320) DEFAULT NULL,
  `LotSize` varchar(320) DEFAULT NULL,
  `ContingencyType` varchar(320) DEFAULT NULL,
  `StreetNumber` varchar(320) DEFAULT NULL,
  `NumberOfFireplaces` int(11) DEFAULT NULL,
  `WaterSource` varchar(64) DEFAULT NULL,
  `CompletionDate` varchar(64) DEFAULT NULL,
  `PermitAvmUse` varchar(64) DEFAULT NULL,
  `MediaUpdateDate` varchar(64) DEFAULT NULL,
  `HeatingSource` varchar(64) DEFAULT NULL,
  `RoofMaterial` varchar(64) DEFAULT NULL,
  `AcreageSource` varchar(64) DEFAULT NULL,
  `StreetName` varchar(320) DEFAULT NULL,
  `GarageDescription` varchar(320) DEFAULT NULL,
  `AgentListPhone` varchar(64) DEFAULT NULL,
  `OfficeListIsIDX` varchar(64) DEFAULT NULL,
  `AgentCoListPhone` varchar(64) DEFAULT NULL,
  `NumOfStories` int(11) NOT NULL,
  `AbsLatitude` decimal(10,0) NOT NULL,
  `AbsLongitude` decimal(10,0) NOT NULL,
  PRIMARY KEY (`MlsNum`)
) ENGINE=InnoDB DEFAULT CHARSET=big5;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `tbl_data_res`
--

DROP TABLE IF EXISTS `tbl_data_res`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `tbl_data_res` (
  `BedroomsThird` varchar(32) DEFAULT NULL,
  `LotNum` varchar(32) DEFAULT NULL,
  `OtherRoomOneDesc` varchar(64) DEFAULT NULL,
  `BedroomTwoDim` varchar(32) DEFAULT NULL,
  `Subdivision` varchar(32) DEFAULT NULL,
  `OfficeListOfficeName` varchar(64) DEFAULT NULL,
  `BedroomTwoDesc` varchar(64) DEFAULT NULL,
  `BedroomsMain` varchar(32) DEFAULT NULL,
  `CoolingSystem` varchar(64) DEFAULT NULL,
  `OvenSource` varchar(64) DEFAULT NULL,
  `OtherRoomOneDim` varchar(64) DEFAULT NULL,
  `DiningRoomDim` varchar(64) DEFAULT NULL,
  `AgentCoListFullName` varchar(320) DEFAULT NULL,
  `FloorTypes` varchar(320) DEFAULT NULL,
  `PoolDesc` varchar(320) DEFAULT NULL,
  `PictureCount` int(11) DEFAULT NULL,
  `BedroomFourDim` varchar(64) DEFAULT NULL,
  `OfficeListPhone` varchar(64) DEFAULT NULL,
  `FullBathsOther` varchar(64) DEFAULT NULL,
  `SqFtOtherDescription` varchar(320) DEFAULT NULL,
  `OvenDesc` varchar(320) DEFAULT NULL,
  `SqFtTotal` decimal(10,0) DEFAULT NULL,
  `MasterBathType` varchar(64) DEFAULT NULL,
  `OfficeListCompanyID` varchar(64) DEFAULT NULL,
  `ListingType` varchar(32) DEFAULT NULL,
  `TotalFullBaths` int(11) DEFAULT NULL,
  `HalfBathsBasement` varchar(64) DEFAULT NULL,
  `InteriorOther` varchar(320) DEFAULT NULL,
  `OfficeCoListPhone` varchar(64) DEFAULT NULL,
  `MasterBathDesc` varchar(320) DEFAULT NULL,
  `AppliancesOther` varchar(320) DEFAULT NULL,
  `GreenCertifyingBody` varchar(64) DEFAULT NULL,
  `ListPrice` decimal(10,0) DEFAULT NULL,
  `CountyID` varchar(32) DEFAULT NULL,
  `OfficeListCode` varchar(64) DEFAULT NULL,
  `BasementType` varchar(64) DEFAULT NULL,
  `Acres` varchar(64) DEFAULT NULL,
  `BedroomsBasement` varchar(64) DEFAULT NULL,
  `HalfBathsThird` varchar(64) DEFAULT NULL,
  `HeatingSystem` varchar(64) DEFAULT NULL,
  `StreetLetter` varchar(64) DEFAULT NULL,
  `RangeDesc` varchar(320) DEFAULT NULL,
  `TotalHalfBaths` int(11) DEFAULT NULL,
  `AreaID` varchar(64) DEFAULT NULL,
  `BedroomThreeDesc` varchar(320) DEFAULT NULL,
  `BuiltInfo` varchar(64) DEFAULT NULL,
  `HighSchool` varchar(64) DEFAULT NULL,
  `PermitExternalComments` varchar(320) DEFAULT NULL,
  `OfficeCoListID` varchar(64) DEFAULT NULL,
  `LotDesc` varchar(320) DEFAULT NULL,
  `YearBuilt` int(11) DEFAULT NULL,
  `AgentListFirstName` varchar(320) DEFAULT NULL,
  `Directions` varchar(1024) DEFAULT NULL,
  `CoolingSource` varchar(64) DEFAULT NULL,
  `NextOpenHouseDate` varchar(64) DEFAULT NULL,
  `ElementarySchool` varchar(64) DEFAULT NULL,
  `AgentCoListFirstName` varchar(64) DEFAULT NULL,
  `LivingRoomDim` varchar(64) DEFAULT NULL,
  `WaterfrontDesc` varchar(320) DEFAULT NULL,
  `ExteriorFeatures` varchar(1024) DEFAULT NULL,
  `Remarks` varchar(1024) DEFAULT NULL,
  `AgentCoListID` varchar(64) DEFAULT NULL,
  `City` varchar(32) DEFAULT NULL,
  `ConstructionType` varchar(64) DEFAULT NULL,
  `DiningRoomDesc` varchar(320) DEFAULT NULL,
  `CommunityAmenities` varchar(1024) DEFAULT NULL,
  `MapNumber` varchar(64) DEFAULT NULL,
  `OfficeListID` varchar(64) DEFAULT NULL,
  `TotalBedrooms` int(11) DEFAULT NULL,
  `PropertyClassID` varchar(64) DEFAULT NULL,
  `LivingRoomDesc` varchar(320) DEFAULT NULL,
  `DenDesc` varchar(320) DEFAULT NULL,
  `State` varchar(32) DEFAULT NULL,
  `HalfBathsMain` varchar(64) DEFAULT NULL,
  `OfficeCoListCode` varchar(64) DEFAULT NULL,
  `PropertySubType` varchar(64) DEFAULT NULL,
  `DrapesRemain` varchar(64) DEFAULT NULL,
  `SqFtBasement` decimal(10,0) DEFAULT NULL,
  `AgentListLastName` varchar(64) DEFAULT NULL,
  `HobbyRoomDim` varchar(64) DEFAULT NULL,
  `KitchenDim` varchar(64) DEFAULT NULL,
  `OpenHouseType` varchar(64) DEFAULT NULL,
  `FullBathsSecond` varchar(64) DEFAULT NULL,
  `RecRoomDesc` varchar(320) DEFAULT NULL,
  `SqFtSecondFloor` decimal(10,0) DEFAULT NULL,
  `SewerSystem` varchar(64) DEFAULT NULL,
  `BedroomsOther` varchar(64) DEFAULT NULL,
  `ModDate` varchar(64) DEFAULT NULL,
  `BedroomsSecond` varchar(64) DEFAULT NULL,
  `StreetDirection` varchar(320) DEFAULT NULL,
  `StreetAddressDisplay` varchar(320) DEFAULT NULL,
  `MlsNum` varchar(64) NOT NULL,
  `ExteriorTrim` varchar(64) DEFAULT NULL,
  `JuniorHighSchool` varchar(64) DEFAULT NULL,
  `IsNewConstruction` varchar(32) DEFAULT NULL,
  `WaterfrontDock` varchar(64) DEFAULT NULL,
  `GarageCapacity` varchar(64) DEFAULT NULL,
  `SqFtMeasurementSource` varchar(64) DEFAULT NULL,
  `HalfBathsSecond` varchar(64) DEFAULT NULL,
  `KitchenDesc` varchar(320) DEFAULT NULL,
  `ElementarySchoolTwo` varchar(64) DEFAULT NULL,
  `Longitude` decimal(10,6) DEFAULT NULL,
  `PatioDeck` varchar(1024) DEFAULT NULL,
  `DenDim` varchar(64) DEFAULT NULL,
  `Latitude` decimal(10,6) DEFAULT NULL,
  `OfficeCoListCompanyID` varchar(64) DEFAULT NULL,
  `AgentListID` varchar(64) DEFAULT NULL,
  `ZipCode` varchar(32) DEFAULT NULL,
  `EnergyFeatures` varchar(1024) DEFAULT NULL,
  `OtherRoomTwoDesc` varchar(320) DEFAULT NULL,
  `RangeSource` varchar(64) DEFAULT NULL,
  `BedroomFourDesc` varchar(320) DEFAULT NULL,
  `FullBathsBasement` varchar(64) DEFAULT NULL,
  `RecRoomDim` varchar(64) DEFAULT NULL,
  `TotalRooms` int(11) DEFAULT NULL,
  `AgentListFullName` varchar(320) DEFAULT NULL,
  `BedroomOneDesc` varchar(320) DEFAULT NULL,
  `OfficeCoListOfficeName` varchar(64) DEFAULT NULL,
  `Style` varchar(64) DEFAULT NULL,
  `DrivewayType` varchar(64) DEFAULT NULL,
  `OtherRoomTwoDim` varchar(64) DEFAULT NULL,
  `HobbyRoomDesc` varchar(320) DEFAULT NULL,
  `FenceType` varchar(64) DEFAULT NULL,
  `HandicapAccess` varchar(64) DEFAULT NULL,
  `SqFtThirdFloor` decimal(10,0) DEFAULT NULL,
  `SqFtMainFloor` decimal(10,0) DEFAULT NULL,
  `AgentCoListLastName` varchar(64) DEFAULT NULL,
  `ListingStatusID` varchar(64) DEFAULT NULL,
  `BedroomOneDim` varchar(64) DEFAULT NULL,
  `MiscOther` varchar(1024) DEFAULT NULL,
  `IsCertifiedGreen` varchar(32) DEFAULT NULL,
  `PrimaryPictureURL` varchar(1024) DEFAULT NULL,
  `NumOfStories` int(11) DEFAULT NULL,
  `TaxAmount` varchar(320) DEFAULT NULL,
  `LotSize` varchar(320) DEFAULT NULL,
  `ContingencyType` varchar(320) DEFAULT NULL,
  `StreetNumber` varchar(320) DEFAULT NULL,
  `NumberOfFireplaces` int(11) DEFAULT NULL,
  `BasementDesc` varchar(320) DEFAULT NULL,
  `WaterSource` varchar(64) DEFAULT NULL,
  `FullBathsMain` varchar(64) DEFAULT NULL,
  `AssociationFee` varchar(64) DEFAULT NULL,
  `CompletionDate` varchar(64) DEFAULT NULL,
  `PermitAvmUse` varchar(64) DEFAULT NULL,
  `MediaUpdateDate` varchar(64) DEFAULT NULL,
  `HeatingSource` varchar(64) DEFAULT NULL,
  `RoofMaterial` varchar(64) DEFAULT NULL,
  `FullBathsThird` varchar(64) DEFAULT NULL,
  `SqFtOther` decimal(10,0) DEFAULT NULL,
  `AcreageSource` varchar(64) DEFAULT NULL,
  `StreetName` varchar(320) DEFAULT NULL,
  `GarageDescription` varchar(320) DEFAULT NULL,
  `HalfBathsOther` varchar(64) DEFAULT NULL,
  `AgentListPhone` varchar(64) DEFAULT NULL,
  `BedroomThreeDim` varchar(64) DEFAULT NULL,
  `AbsLatitude` decimal(10,0) NOT NULL,
  `AbsLongitude` decimal(10,0) NOT NULL,
  PRIMARY KEY (`MlsNum`)
) ENGINE=InnoDB DEFAULT CHARSET=big5;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `tbl_data_rnt`
--

DROP TABLE IF EXISTS `tbl_data_rnt`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `tbl_data_rnt` (
  `BedroomsThird` varchar(32) DEFAULT NULL,
  `OtherRoomOneDesc` varchar(64) DEFAULT NULL,
  `BedroomTwoDim` varchar(32) DEFAULT NULL,
  `Subdivision` varchar(32) DEFAULT NULL,
  `OfficeListOfficeName` varchar(64) DEFAULT NULL,
  `BedroomTwoDesc` varchar(64) DEFAULT NULL,
  `BedroomsMain` varchar(32) DEFAULT NULL,
  `CoolingSystem` varchar(64) DEFAULT NULL,
  `OtherRoomOneDim` varchar(64) DEFAULT NULL,
  `DiningRoomDim` varchar(64) DEFAULT NULL,
  `AgentCoListFullName` varchar(320) DEFAULT NULL,
  `FloorTypes` varchar(320) DEFAULT NULL,
  `PoolDesc` varchar(320) DEFAULT NULL,
  `PictureCount` int(11) DEFAULT NULL,
  `BedroomFourDim` varchar(64) DEFAULT NULL,
  `OfficeListPhone` varchar(64) DEFAULT NULL,
  `FullBathsOther` varchar(64) DEFAULT NULL,
  `SqFtOtherDescription` varchar(320) DEFAULT NULL,
  `SqFtTotal` decimal(10,0) DEFAULT NULL,
  `OfficeListCompanyID` varchar(64) DEFAULT NULL,
  `TotalFullBaths` int(11) DEFAULT NULL,
  `HalfBathsBasement` varchar(64) DEFAULT NULL,
  `InteriorOther` varchar(320) DEFAULT NULL,
  `OfficeCoListPhone` varchar(64) DEFAULT NULL,
  `AppliancesOther` varchar(320) DEFAULT NULL,
  `GreenCertifyingBody` varchar(64) DEFAULT NULL,
  `CountyID` varchar(32) DEFAULT NULL,
  `OfficeListCode` varchar(64) DEFAULT NULL,
  `BasementType` varchar(64) DEFAULT NULL,
  `BedroomsBasement` varchar(64) DEFAULT NULL,
  `HalfBathsThird` varchar(64) DEFAULT NULL,
  `HeatingSystem` varchar(64) DEFAULT NULL,
  `StreetLetter` varchar(64) DEFAULT NULL,
  `TotalHalfBaths` int(11) DEFAULT NULL,
  `AreaID` varchar(64) DEFAULT NULL,
  `BedroomThreeDesc` varchar(320) DEFAULT NULL,
  `BuiltInfo` varchar(64) DEFAULT NULL,
  `HighSchool` varchar(64) DEFAULT NULL,
  `PermitExternalComments` varchar(320) DEFAULT NULL,
  `OfficeCoListID` varchar(64) DEFAULT NULL,
  `YearBuilt` int(11) DEFAULT NULL,
  `AgentListFirstName` varchar(320) DEFAULT NULL,
  `Directions` varchar(1024) DEFAULT NULL,
  `CoolingSource` varchar(64) DEFAULT NULL,
  `NextOpenHouseDate` varchar(64) DEFAULT NULL,
  `ElementarySchool` varchar(64) DEFAULT NULL,
  `AgentCoListFirstName` varchar(64) DEFAULT NULL,
  `LivingRoomDim` varchar(64) DEFAULT NULL,
  `WaterfrontDesc` varchar(320) DEFAULT NULL,
  `ExteriorFeatures` varchar(1024) DEFAULT NULL,
  `Remarks` varchar(1024) DEFAULT NULL,
  `AgentCoListID` varchar(64) DEFAULT NULL,
  `City` varchar(32) DEFAULT NULL,
  `ConstructionType` varchar(64) DEFAULT NULL,
  `DiningRoomDesc` varchar(320) DEFAULT NULL,
  `CommunityAmenities` varchar(1024) DEFAULT NULL,
  `OfficeListID` varchar(64) DEFAULT NULL,
  `TotalBedrooms` int(11) DEFAULT NULL,
  `PropertyClassID` varchar(64) DEFAULT NULL,
  `LivingRoomDesc` varchar(320) DEFAULT NULL,
  `DenDesc` varchar(320) DEFAULT NULL,
  `State` varchar(32) DEFAULT NULL,
  `HalfBathsMain` varchar(64) DEFAULT NULL,
  `OfficeCoListCode` varchar(64) DEFAULT NULL,
  `AvailableDate` varchar(64) DEFAULT NULL,
  `PropertySubType` varchar(64) DEFAULT NULL,
  `SqFtBasement` decimal(10,0) DEFAULT NULL,
  `AgentListLastName` varchar(64) DEFAULT NULL,
  `HobbyRoomDim` varchar(64) DEFAULT NULL,
  `KitchenDim` varchar(64) DEFAULT NULL,
  `OpenHouseType` varchar(64) DEFAULT NULL,
  `FullBathsSecond` varchar(64) DEFAULT NULL,
  `RecRoomDesc` varchar(320) DEFAULT NULL,
  `SqFtSecondFloor` decimal(10,0) DEFAULT NULL,
  `SewerSystem` varchar(64) DEFAULT NULL,
  `BedroomsOther` varchar(64) DEFAULT NULL,
  `ModDate` varchar(64) DEFAULT NULL,
  `BedroomsSecond` varchar(64) DEFAULT NULL,
  `StreetDirection` varchar(320) DEFAULT NULL,
  `StreetAddressDisplay` varchar(320) DEFAULT NULL,
  `MlsNum` varchar(64) NOT NULL,
  `ExteriorTrim` varchar(64) DEFAULT NULL,
  `JuniorHighSchool` varchar(64) DEFAULT NULL,
  `WaterfrontDock` varchar(64) DEFAULT NULL,
  `GarageCapacity` varchar(64) DEFAULT NULL,
  `HalfBathsSecond` varchar(64) DEFAULT NULL,
  `KitchenDesc` varchar(320) DEFAULT NULL,
  `ElementarySchoolTwo` varchar(64) DEFAULT NULL,
  `Longitude` decimal(10,6) DEFAULT NULL,
  `PatioDeck` varchar(1024) DEFAULT NULL,
  `DenDim` varchar(64) DEFAULT NULL,
  `Latitude` decimal(10,6) DEFAULT NULL,
  `OfficeCoListCompanyID` varchar(64) DEFAULT NULL,
  `AgentListID` varchar(64) DEFAULT NULL,
  `ZipCode` varchar(32) DEFAULT NULL,
  `EnergyFeatures` varchar(1024) DEFAULT NULL,
  `OtherRoomTwoDesc` varchar(320) DEFAULT NULL,
  `BedroomFourDesc` varchar(320) DEFAULT NULL,
  `FullBathsBasement` varchar(64) DEFAULT NULL,
  `RecRoomDim` varchar(64) DEFAULT NULL,
  `TotalRooms` int(11) DEFAULT NULL,
  `AgentListFullName` varchar(320) DEFAULT NULL,
  `BedroomOneDesc` varchar(320) DEFAULT NULL,
  `OfficeCoListOfficeName` varchar(64) DEFAULT NULL,
  `DrivewayType` varchar(64) DEFAULT NULL,
  `OtherRoomTwoDim` varchar(64) DEFAULT NULL,
  `HobbyRoomDesc` varchar(320) DEFAULT NULL,
  `FenceType` varchar(64) DEFAULT NULL,
  `HandicapAccess` varchar(64) DEFAULT NULL,
  `SqFtThirdFloor` decimal(10,0) DEFAULT NULL,
  `SqFtMainFloor` decimal(10,0) DEFAULT NULL,
  `AgentCoListLastName` varchar(64) DEFAULT NULL,
  `ListingStatusID` varchar(64) DEFAULT NULL,
  `BedroomOneDim` varchar(64) DEFAULT NULL,
  `MiscOther` varchar(1024) DEFAULT NULL,
  `IsCertifiedGreen` varchar(32) DEFAULT NULL,
  `PrimaryPictureURL` varchar(1024) DEFAULT NULL,
  `NumOfStories` int(11) DEFAULT NULL,
  `StreetNumber` varchar(320) DEFAULT NULL,
  `NumberOfFireplaces` int(11) DEFAULT NULL,
  `BasementDesc` varchar(320) DEFAULT NULL,
  `WaterSource` varchar(64) DEFAULT NULL,
  `FullBathsMain` varchar(64) DEFAULT NULL,
  `PermitAvmUse` varchar(64) DEFAULT NULL,
  `MediaUpdateDate` varchar(64) DEFAULT NULL,
  `HeatingSource` varchar(64) DEFAULT NULL,
  `RoofMaterial` varchar(64) DEFAULT NULL,
  `FullBathsThird` varchar(64) DEFAULT NULL,
  `SqFtOther` decimal(10,0) DEFAULT NULL,
  `StreetName` varchar(320) DEFAULT NULL,
  `GarageDescription` varchar(320) DEFAULT NULL,
  `HalfBathsOther` varchar(64) DEFAULT NULL,
  `AgentListPhone` varchar(64) DEFAULT NULL,
  `BedroomThreeDim` varchar(64) DEFAULT NULL,
  `AbsLatitude` decimal(10,0) NOT NULL,
  `AbsLongitude` decimal(10,0) NOT NULL,
  `LeasePerMonth` decimal(10,0) NOT NULL,
  `ElectricityPaidBy` varchar(320) DEFAULT NULL,
  `GasPaidBy` varchar(320) DEFAULT NULL,
  `MinimumLease` decimal(10,0) NOT NULL,
  `VerticalLocation` varchar(320) DEFAULT NULL,
  `IsFurnished` varchar(32) DEFAULT NULL,
  `SmokingPermitted` varchar(32) DEFAULT NULL,
  `HasRange` varchar(32) DEFAULT NULL,
  `PetsPermitted` varchar(32) DEFAULT NULL,
  `OfficeListIsIDX` varchar(320) DEFAULT NULL,
  `HorizontalLocation` varchar(320) DEFAULT NULL,
  `MailBox` varchar(320) DEFAULT NULL,
  `PetDeposit` decimal(10,0) NOT NULL,
  `WaterPaidBy` varchar(320) DEFAULT NULL,
  `HasRefrigerator` varchar(32) DEFAULT NULL,
  `Laundry` varchar(64) DEFAULT NULL,
  `SecurityDeposit` decimal(10,0) NOT NULL,
  `UnitNumber` varchar(64) DEFAULT NULL,
  `AgentCoListPhone` varchar(320) NOT NULL,
  PRIMARY KEY (`MlsNum`)
) ENGINE=InnoDB DEFAULT CHARSET=big5;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `tbl_keys`
--

DROP TABLE IF EXISTS `tbl_keys`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `tbl_keys` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `key` varchar(40) NOT NULL,
  `description` varchar(256) DEFAULT NULL,
  `level` int(2) NOT NULL,
  `ignore_limits` tinyint(1) NOT NULL DEFAULT '0',
  `date_created` int(11) NOT NULL,
  `active` bit(1) NOT NULL,
  `deactivation_message` varchar(1024) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `tbl_media_cnd`
--

DROP TABLE IF EXISTS `tbl_media_cnd`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `tbl_media_cnd` (
  `ModDate` varchar(32) DEFAULT NULL,
  `DisplayOrder` int(11) NOT NULL,
  `MediaDescription` varchar(320) DEFAULT NULL,
  `ListingStatusID` varchar(32) DEFAULT NULL,
  `PhotoHR` varchar(320) DEFAULT NULL,
  `OfficeListCompanyID` varchar(32) DEFAULT NULL,
  `PropertyClassID` varchar(32) DEFAULT NULL,
  `AreaID` varchar(32) DEFAULT NULL,
  `CreateDate` varchar(32) DEFAULT NULL,
  `OfficeListCode` varchar(32) DEFAULT NULL,
  `MediaType` varchar(32) DEFAULT NULL,
  `URL` varchar(320) DEFAULT NULL,
  `MlsNum` varchar(64) NOT NULL,
  `AgentListID` varchar(32) DEFAULT NULL,
  `PhotoLR` varchar(320) DEFAULT NULL,
  `OfficeListID` varchar(45) DEFAULT NULL,
  `IsPrimary` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`MlsNum`,`DisplayOrder`)
) ENGINE=InnoDB DEFAULT CHARSET=big5;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `tbl_media_res`
--

DROP TABLE IF EXISTS `tbl_media_res`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `tbl_media_res` (
  `ModDate` varchar(32) DEFAULT NULL,
  `DisplayOrder` int(11) NOT NULL,
  `MediaDescription` varchar(320) DEFAULT NULL,
  `ListingStatusID` varchar(32) DEFAULT NULL,
  `PhotoHR` varchar(320) DEFAULT NULL,
  `OfficeListCompanyID` varchar(32) DEFAULT NULL,
  `PropertyClassID` varchar(32) DEFAULT NULL,
  `AreaID` varchar(32) DEFAULT NULL,
  `CreateDate` varchar(32) DEFAULT NULL,
  `OfficeListCode` varchar(32) DEFAULT NULL,
  `MediaType` varchar(32) DEFAULT NULL,
  `URL` varchar(320) DEFAULT NULL,
  `MlsNum` varchar(64) NOT NULL,
  `AgentListID` varchar(32) DEFAULT NULL,
  `PhotoLR` varchar(320) DEFAULT NULL,
  `OfficeListID` varchar(45) DEFAULT NULL,
  `IsPrimary` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`DisplayOrder`,`MlsNum`)
) ENGINE=InnoDB DEFAULT CHARSET=big5;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `tbl_stats`
--

DROP TABLE IF EXISTS `tbl_stats`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `tbl_stats` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `device_id` varchar(40) DEFAULT NULL,
  `address_search_terms` varchar(128) DEFAULT NULL,
  `location_latitude` decimal(10,6) DEFAULT NULL,
  `location_longitude` decimal(10,6) DEFAULT NULL,
  `property_type` varchar(32) DEFAULT NULL,
  `listprice_min` decimal(10,0) DEFAULT NULL,
  `listprice_max` decimal(10,0) DEFAULT NULL,
  `bedrooms_min` int(11) DEFAULT NULL,
  `bathrooms_min` int(11) DEFAULT NULL,
  `sqft_min` decimal(10,0) DEFAULT NULL,
  `sqft_max` decimal(10,0) DEFAULT NULL,
  `yearbuilt_min` int(11) DEFAULT NULL,
  `yearbuilt_max` int(11) DEFAULT NULL,
  `timestamp` datetime DEFAULT NULL,
  `lt_location_latitude` decimal(10,6) DEFAULT NULL,
  `lt_location_longitude` decimal(10,6) DEFAULT NULL,
  `br_location_latitude` decimal(10,6) DEFAULT NULL,
  `br_location_longitude` decimal(10,6) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=big5;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `tbl_stats_aae83365b1eb117e461e529b264e04b1`
--

DROP TABLE IF EXISTS `tbl_stats_aae83365b1eb117e461e529b264e04b1`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `tbl_stats_aae83365b1eb117e461e529b264e04b1` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `device_id` varchar(40) DEFAULT NULL,
  `address_search_terms` varchar(128) DEFAULT NULL,
  `location_latitude` decimal(10,6) DEFAULT NULL,
  `location_longitude` decimal(10,6) DEFAULT NULL,
  `property_type` varchar(32) DEFAULT NULL,
  `listprice_min` decimal(10,0) DEFAULT NULL,
  `listprice_max` decimal(10,0) DEFAULT NULL,
  `bedrooms_min` int(11) DEFAULT NULL,
  `bathrooms_min` int(11) DEFAULT NULL,
  `sqft_min` decimal(10,0) DEFAULT NULL,
  `sqft_max` decimal(10,0) DEFAULT NULL,
  `yearbuilt_min` int(11) DEFAULT NULL,
  `yearbuilt_max` int(11) DEFAULT NULL,
  `timestamp` datetime DEFAULT NULL,
  `lt_location_latitude` decimal(10,6) DEFAULT NULL,
  `lt_location_longitude` decimal(10,6) DEFAULT NULL,
  `br_location_latitude` decimal(10,6) DEFAULT NULL,
  `br_location_longitude` decimal(10,6) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=133 DEFAULT CHARSET=big5;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `tbl_stats_allison`
--

DROP TABLE IF EXISTS `tbl_stats_allison`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `tbl_stats_allison` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `device_id` varchar(40) DEFAULT NULL,
  `address_search_terms` varchar(128) DEFAULT NULL,
  `location_latitude` decimal(10,6) DEFAULT NULL,
  `location_longitude` decimal(10,6) DEFAULT NULL,
  `property_type` varchar(32) DEFAULT NULL,
  `listprice_min` decimal(10,0) DEFAULT NULL,
  `listprice_max` decimal(10,0) DEFAULT NULL,
  `bedrooms_min` int(11) DEFAULT NULL,
  `bathrooms_min` int(11) DEFAULT NULL,
  `sqft_min` decimal(10,0) DEFAULT NULL,
  `sqft_max` decimal(10,0) DEFAULT NULL,
  `yearbuilt_min` int(11) DEFAULT NULL,
  `yearbuilt_max` int(11) DEFAULT NULL,
  `timestamp` datetime DEFAULT NULL,
  `lt_location_latitude` decimal(10,6) DEFAULT NULL,
  `lt_location_longitude` decimal(10,6) DEFAULT NULL,
  `br_location_latitude` decimal(10,6) DEFAULT NULL,
  `br_location_longitude` decimal(10,6) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=big5;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `tbl_stats_cindy`
--

DROP TABLE IF EXISTS `tbl_stats_cindy`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `tbl_stats_cindy` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `device_id` varchar(40) DEFAULT NULL,
  `address_search_terms` varchar(128) DEFAULT NULL,
  `location_latitude` decimal(10,6) DEFAULT NULL,
  `location_longitude` decimal(10,6) DEFAULT NULL,
  `property_type` varchar(32) DEFAULT NULL,
  `listprice_min` decimal(10,0) DEFAULT NULL,
  `listprice_max` decimal(10,0) DEFAULT NULL,
  `bedrooms_min` int(11) DEFAULT NULL,
  `bathrooms_min` int(11) DEFAULT NULL,
  `sqft_min` decimal(10,0) DEFAULT NULL,
  `sqft_max` decimal(10,0) DEFAULT NULL,
  `yearbuilt_min` int(11) DEFAULT NULL,
  `yearbuilt_max` int(11) DEFAULT NULL,
  `timestamp` datetime DEFAULT NULL,
  `lt_location_latitude` decimal(10,6) DEFAULT NULL,
  `lt_location_longitude` decimal(10,6) DEFAULT NULL,
  `br_location_latitude` decimal(10,6) DEFAULT NULL,
  `br_location_longitude` decimal(10,6) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=big5;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `tbl_stats_lisa`
--

DROP TABLE IF EXISTS `tbl_stats_lisa`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `tbl_stats_lisa` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `device_id` varchar(40) DEFAULT NULL,
  `address_search_terms` varchar(128) DEFAULT NULL,
  `location_latitude` decimal(10,6) DEFAULT NULL,
  `location_longitude` decimal(10,6) DEFAULT NULL,
  `property_type` varchar(32) DEFAULT NULL,
  `listprice_min` decimal(10,0) DEFAULT NULL,
  `listprice_max` decimal(10,0) DEFAULT NULL,
  `bedrooms_min` int(11) DEFAULT NULL,
  `bathrooms_min` int(11) DEFAULT NULL,
  `sqft_min` decimal(10,0) DEFAULT NULL,
  `sqft_max` decimal(10,0) DEFAULT NULL,
  `yearbuilt_min` int(11) DEFAULT NULL,
  `yearbuilt_max` int(11) DEFAULT NULL,
  `timestamp` datetime DEFAULT NULL,
  `lt_location_latitude` decimal(10,6) DEFAULT NULL,
  `lt_location_longitude` decimal(10,6) DEFAULT NULL,
  `br_location_latitude` decimal(10,6) DEFAULT NULL,
  `br_location_longitude` decimal(10,6) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1188 DEFAULT CHARSET=big5;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;